In [ ]:
#csv파일로 저장
#DataFrame 객체.to_csv("파일이름(경로)")

In [2]:
# 라이브러리 불러오기
import pandas as pd

# 판다스 DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장 
data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')   #name 열을 인덱스로 지정

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [3]:
df.to_csv("./data/df_sample.csv")

In [4]:
df.to_csv("./data/df_sample_no_index.csv", index=False)

In [ ]:
#json파일로 저장
#DataFrame 객체.to_json("파일이름(경로)")

In [2]:
# 라이브러리 불러오기
import pandas as pd

# 판다스 DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장 
data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')   #name 열을 인덱스로 지정

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [3]:
df.to_json("./data/df_sample.json")

In [6]:
df.to_json("./data/df_sample_split.json", orient="split")

In [7]:
df.to_json("./data/df_sample_records.json", orient="records")

In [8]:
df.to_json("./data/df_sample_index.json", orient="index")

In [9]:
df.to_json("./data/df_sample_columns.json", orient="columns")

In [10]:
df.to_json("./data/df_sample_values.json", orient="values")

In [ ]:
#Excel로 저장
#DataFrame객체.to_excel("파일이름(경로)")

# 라이브러리 불러오기
import pandas as pd

# 판다스 DataFrame() 함수로 데이터프레임 변환. 변수 df에 저장 
data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df = df.set_index('name')   #name 열을 인덱스로 지정

df